---

version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: ./lint.sh

workflows:
  version: 2
  build:
    - job1:
        branches:
          ignore:
            - gh-pages
